program test_exception

  use exception_tests, ONLY: test_catch

  call test_catch()

end program test_exception
