program test_exception

  use exception_tests, ONLY: test_fail

  call test_fail()

end program test_exception
